name: pydata_nyc20173.6
channels:
- conda-forge
- defaults
dependencies:
- backports=1.0=py36_1
- backports.functools_lru_cache=1.4=py36_1
- cycler=0.10.0=py36_0
- freetype=2.7=1
- h5py=2.7.1=py36_2
- hdf5=1.10.1=1
- joblib=0.11=py36_0
- libgpuarray=0.7.5=0
- libpng=1.6.34=0
- mako=1.0.7=py36_0
- markupsafe=1.0=py36_0
- matplotlib=2.1.0=py36_0
- pandas=0.21.0=py36_0
- patsy=0.4.1=py36_0
- pygpu=0.7.5=py36_0
- pymc3=3.2=py36_0
- pyparsing=2.2.0=py36_0
- python-dateutil=2.6.1=py36_0
- pytz=2017.3=py_2
- six=1.11.0=py36_1
- theano=0.9.0=py36_1
- tornado=4.5.2=py36_0
- tqdm=4.19.4=py_0
- appnope=0.1.0=py36hf537a9a_0
- bleach=2.0.0=py36h8fcea71_0
- ca-certificates=2017.08.26=ha1e5d58_0
- certifi=2017.11.5=py36ha569be9_0
- dbus=1.10.22=h50d9ad6_0
- decorator=4.1.2=py36h69a1b52_0
- entrypoints=0.2.3=py36hd81d71f_2
- expat=2.2.5=hb8e80ba_0
- gettext=0.19.8.1=h15daf44_3
- glib=2.53.6=h33f6a65_2
- html5lib=0.999999999=py36h79312fd_0
- icu=58.2=h4b95b61_1
- intel-openmp=2018.0.0=h8158457_8
- ipykernel=4.6.1=py36h3208c25_0
- ipython=6.2.1=py36h3dda519_1
- ipython_genutils=0.2.0=py36h241746c_0
- ipywidgets=7.0.5=py36h5142716_0
- jedi=0.10.2=py36h6325097_0
- jinja2=2.9.6=py36hde4beb4_1
- jpeg=9b=he5867d9_2
- jsonschema=2.6.0=py36hb385e00_0
- jupyter=1.0.0=py36h598a6cc_0
- jupyter_client=5.1.0=py36hf6c435f_0
- jupyter_console=5.2.0=py36hccf5b1c_1
- jupyter_core=4.4.0=py36h79cf704_0
- libcxx=4.0.1=h579ed51_0
- libcxxabi=4.0.1=hebd6815_0
- libedit=3.1=hb4e282d_0
- libffi=3.2.1=h475c297_4
- libgfortran=3.0.1=h93005f0_2
- libiconv=1.15=hdd342a3_7
- libsodium=1.0.15=hd9e47c5_0
- mistune=0.8.1=py36h638d0ca_0
- mkl=2018.0.1=hfbd8650_4
- nbconvert=5.3.1=py36h810822e_0
- nbformat=4.4.0=py36h827af21_0
- ncurses=6.0=hd04f020_2
- notebook=5.2.1=py36h640abe8_0
- numpy=1.13.3=py36h2cdce51_0
- openssl=1.0.2m=h86d3e6a_1
- pandoc=1.19.2.1=ha5e8f32_1
- pandocfilters=1.4.2=py36h3b0b094_1
- pcre=8.41=hfb6ab37_1
- pexpect=4.3.0=py36h427ab81_0
- pickleshare=0.7.4=py36hf512f8e_0
- pip=9.0.1=py36h1555ced_4
- prompt_toolkit=1.0.15=py36haeda067_0
- ptyprocess=0.5.2=py36he6521c3_0
- pygments=2.2.0=py36h240cd3f_0
- pyqt=5.6.0=py36he5c6137_6
- python=3.6.3=h5ce8c04_4
- pyzmq=16.0.3=py36he48b5ad_0
- qt=5.6.2=h9975529_14
- qtconsole=4.3.1=py36hd96c0ff_0
- readline=7.0=hc1231fa_4
- scikit-learn=0.19.1=py36hffbff8c_0
- scipy=1.0.0=py36h1de22e9_0
- seaborn=0.8.1=py36h595ecd9_0
- setuptools=36.5.0=py36h2134326_0
- simplegeneric=0.8.1=py36he5b5b09_0
- sip=4.18.1=py36h2824476_2
- sqlite=3.20.1=h7e4c145_2
- statsmodels=0.8.0=py36h9c68fc9_0
- terminado=0.6=py36h656782e_0
- testpath=0.3.1=py36h625a49b_0
- tk=8.6.7=h35a86e2_3
- traitlets=4.3.2=py36h65bd3ce_0
- wcwidth=0.1.7=py36h8c6ec74_0
- webencodings=0.5.1=py36h3b9701d_1
- wheel=0.30.0=py36h5eb2c71_1
- widgetsnbextension=3.0.8=py36h34759f8_0
- xz=5.2.3=h0278029_2
- zeromq=4.2.2=ha360ad0_2
- zlib=1.2.11=hf3cbc9b_2
- pip:
  - backports.functools-lru-cache==1.4
  - ipython-genutils==0.2.0
  - jupyter-client==5.1.0
  - jupyter-console==5.2.0
  - jupyter-core==4.4.0
  - prompt-toolkit==1.0.15
  - sampled==0.1.2
